"""empty message

Revision ID: 2258610c4832
Revises: 4fc803af1316
Create Date: 2015-01-19 12:31:59.045940

"""

# revision identifiers, used by Alembic.
revision = '2258610c4832'
down_revision = '4fc803af1316'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import DDL


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_place_of_inquiry', sa.Column('coordinates_validated', sa.BOOLEAN(), nullable=False, server_default=sa.text('false')))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_place_of_inquiry', 'coordinates_validated')
    ### end Alembic commands ###
