"""empty message

Revision ID: 44f16b57d26f
Revises: 1d30bb17d08d
Create Date: 2015-04-23 11:14:29.372866

"""

# revision identifiers, used by Alembic.
revision = '44f16b57d26f'
down_revision = '1d30bb17d08d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_sheet_entry', sa.Column('extraction_date', sa.DateTime()))
    ### end Alembic commands ###
    

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_sheet_entry', 'extraction_date')
    ### end Alembic commands ###
