"""empty message

Revision ID: 4fc803af1316
Revises: 4c0accdc7392
Create Date: 2014-11-21 14:06:21.678872

"""

# revision identifiers, used by Alembic.
revision = '4fc803af1316'
down_revision = '4c0accdc7392'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_place_of_inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pointcode_old', sa.Text(), nullable=True),
    sa.Column('pointcode_new', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('language_group', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pointcode_new'),
    sa.UniqueConstraint('pointcode_old')
    )
    op.create_table('tbl_place_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_of_inquiry_fkey', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('country_code', sa.CHAR(2), nullable=True),
    sa.Column('source', sa.Enum('google.com', 'geonames.org', name='candidate_source'), nullable=True),
    sa.Column('feature_code', sa.Text(), nullable=True),
    sa.Column('complete_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['place_of_inquiry_fkey'], ['tbl_place_of_inquiry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_place_candidate')
    op.drop_table('tbl_place_of_inquiry')
    ### end Alembic commands ###
